server {
    listen 8080;

    location /api/ {
        proxy_pass http://service-a/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host service-a;
        proxy_set_header X-Sandbox-ID $http_x_sandbox_id;
        proxy_pass_request_headers on;
    }

    location /mocks/ {
        proxy_pass http://mock-manager/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host mock-manager;
        proxy_pass_request_headers on;
    }

    location /sandboxes-api/ {
        proxy_pass http://sandbox-api/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host sandbox-api;
        proxy_pass_request_headers on;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
