apiVersion: sandbox.poc/v1
kind: Sandbox
metadata:
  name: test-123
spec:
  services:
    - name: service-c
      env:
        - name: DATABASE_URL
          value: postgresql://poc:poc@postgres-sandbox:5432/catalog
        - name: DB_PEER_SERVICE
          value: postgres-sandbox
        - name: DB_SCHEMA
          value: split
    - name: service-e
      env:
        - name: DATABASE_URL
          value: postgresql://poc:poc@postgres-sandbox:5432/catalog
        - name: DB_PEER_SERVICE
          value: postgres-sandbox
        - name: DB_SCHEMA
          value: split
  mocks:
    - host: external-payments
      method: POST
      path: /charge
      status: 402
      body:
        error: card_declined
