from typing import Protocol

from domain.sandbox import BaselineDeployment


class SandboxPort(Protocol):
    def list_sandboxes(self) -> list[dict]: ...

    def get_sandbox(self, name: str) -> dict | None: ...

    def create_sandbox(self, body: dict) -> dict: ...

    def delete_sandbox(self, name: str) -> None: ...

    def list_baseline_deployments(self) -> list[BaselineDeployment]: ...
