apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: external-weather
spec:
  hosts:
    - external-weather.external.svc.cluster.local
  http:
    - name: sandbox-route
      match:
        - headers:
            x-sandbox-id:
              regex: .+
      route:
        - destination:
            host: mock-proxy.default.svc.cluster.local
      timeout: 5s
      retries:
        attempts: 2
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,unavailable
    - name: baseline-route
      route:
        - destination:
            host: external-weather.external.svc.cluster.local
