from typing import Protocol

from domain.mocks import ExistingMockRule
from domain.models import MockRuleSpec, Sandbox, SandboxRouteTarget


class DeploymentGateway(Protocol):
    def get_baseline(self, service_name: str) -> dict: ...

    def apply_sandbox_deployment(self, manifest: dict, owner: Sandbox) -> None: ...

    def delete_sandbox_deployment(self, service_name: str, sandbox_id: str) -> None: ...

    def list_managed_service_names(self, sandbox_id: str) -> tuple[str, ...]: ...

    def is_ready(self, service_name: str, sandbox_id: str) -> bool: ...


class RoutingGateway(Protocol):
    def route_targets(self, service_name: str) -> tuple[SandboxRouteTarget, ...]: ...

    def apply_destination_rule(self, manifest: dict) -> None: ...

    def apply_virtual_service(self, manifest: dict) -> None: ...

    def delete_destination_rule(self, service_name: str) -> None: ...

    def delete_virtual_service(self, service_name: str) -> None: ...


class MockGateway(Protocol):
    def list_rules(self, sandbox_id: str) -> tuple[ExistingMockRule, ...]: ...

    def list_all_rules(self) -> tuple[ExistingMockRule, ...]: ...

    def create_rule(self, sandbox_id: str, mock: MockRuleSpec) -> None: ...

    def delete_rule(self, rule_id: str) -> None: ...
